### ISSUE TITLE
Confidential Strategies

### ISSUE THREAD

**Issue by mikenew** [skyzeio/Skyze#4]
How to hide the content of confidential trading strategy files?

**Comment by utx0** [comment]
What does this mean exactly?

**Comment by mikenew** [comment]
can i push a file to my github repo

and then not have it propagate to the org repo in pull requests?

As people may want to protect their trading IP.

**Comment by mikenew** [comment]
so people can code their own strategies, have them under their own git but not share them with the rest of the world

**Comment by utx0** [comment]
no, we would have to build a plugin architecture... Which we should do anyway...

**Comment by mikenew** [comment]
Of course!
